#DATALOADER:
#  TRAIN_X:
#    BATCH_SIZE: 32
#  TEST:
#    BATCH_SIZE: 100
#  NUM_WORKERS: 8
#
#INPUT:
#  SIZE: (224, 224)
#  INTERPOLATION: "bicubic"
#  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
#  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
#  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
#
#OPTIM:
#  NAME: "sgd"
#  LR: 0.002
#  MAX_EPOCH: 200
#  LR_SCHEDULER: "cosine"
#  WARMUP_EPOCH: 1
#  WARMUP_TYPE: "constant"
#  WARMUP_CONS_LR: 1e-5
#
#TRAIN:
#  PRINT_FREQ: 5
#
#MODEL:
#  BACKBONE:
#    NAME: "ViT-B/16"

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.14694904, 0.14694904, 0.14694904]
  PIXEL_STD: [0.13213828, 0.13213828, 0.13213828]
#  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  RANDAUGMENT_N: 3
  RANDAUGMENT_M: 10
#  TRANSFORMS: ["randaugment_fixmatch", "normalize"]
#  TRANSFORMS: ["random_flip", "normalize"]
  TRANSFORMS: ["randaugment"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 300
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"